### ISSUE TITLE
Elm-format not working when installed as a package

### ISSUE THREAD

**Issue by martimatix** [dillonkearns/graphqelm#10]
Apologies Dillon - my elm-format patch is breaking prod at the moment.

The issue is that `.bin` doesn't get populated when graphqelm gets installed as a module.

Currently looking into a fix for this.

**Comment by martimatix** [comment]
For a global installation, it looks like it might be as simple as moving elm-format from `devDependencies` to `dependencies` in `package.json`.

For local installs, `.bin` is one level up. Currently looking into a way to get around this.

**Comment by martimatix** [comment]
I opened a PR to fix this: https://github.com/dillonkearns/graphqelm/pull/11

**Comment by dillonkearns** [comment]
Merged 👍
