### ISSUE TITLE
Allow enum types starting with underscore

### ISSUE THREAD

**Issue by mkaulig** [dillonkearns/graphqelm#13]
GraphQL enum types, which start with an underscore are converted to elm modules that start with an underscore, which is not valid elm code.

APIs generated with graph.cool use an enum type, wich starts with an underscore. Here is the corresponding part of the introspection query:

```
{
          "inputFields": null,
          "name": "_ModelMutationType",
          "description": null,
          "interfaces": null,
          "enumValues": [
            {
              "name": "CREATED",
              "description": null,
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "UPDATED",
              "description": null,
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "DELETED",
              "description": null,
              "isDeprecated": false,
              "deprecationReason": null
            }
          ],
          "fields": null,
          "kind": "ENUM",
          "possibleTypes": null
        }
```

**Comment by dillonkearns** [comment]
@mkaulig thank you for reporting, and thanks for the very clear issue! I should be able to get a fix out for this and #12 within the next few days.

**Comment by dillonkearns** [comment]
@mkaulig I've released a fix for this with elm package version `4.0.0` and CLI version `0.0.10`!

I am normalizing all argument, field, union constructor, and type (i.e. module) names so any valid GraphQL name (even non-idiomatic ones) should generate valid elm syntax now.

I'm also normalizing to a format that is more idiomatic in Elm, so an enum values `EMPIRE`, `JEDI`, and `NEWHOPE` would generate the union
```
type Episode
    = Empire
    | Jedi
    | Newhope
```

If you wouldn't mind, it would be great to get a confirmation that this fixes the issue for you when you get a chance. Thanks!

**Comment by mkaulig** [comment]
The original issue with the enum name is fixed for me with this new version.

I just realised that I also have one object type starting with an underscore in my API. The module in Api/Object/ is generated with normalized names now, which is correct.
However the file Api/Object.elm still has a type with the underscore prefixed instead of postfixed. Maybe the Object.elm file is not included in the normalization, yet?

Thanks for the great work! I will try to prepare a PR to get this file also normalized.

**Comment by dillonkearns** [comment]
@mkaulig thanks for reporting back! You're right, I wasn't normalizing the names in that file. I need to swing back around and use an opaque type for the module names like I did for field names and enum names. That ensures that the only way to get the name is to explicitly say give me the raw name or give me the normalized name, so it's less error-prone.

For now, I've added an end-to-end test case for this and pushed up a fix with npm package version 0.0.11. I believe this should resolve your issue. Thanks for helping me get through these issues, I appreciate it!

**Comment by dillonkearns** [comment]
Oh yes, and you may need to remove all the files in your `Api` folder before rerunning `graphqelm`. There is an outstanding issue where the CLI doesn't remove the files before running. I'm working on a fix for that, but for now just removing all the files in that folder manually first should do the trick.

**Comment by mkaulig** [comment]
Thanks! The new version resolves the issue!

**Comment by dillonkearns** [comment]
Great, I'm glad it's working out! I just published a new version with the opaque type refactoring, as well, so I think there are now plenty of safeguards to ensure that the normalization code doesn't break.

**Comment by dillonkearns** [comment]
So @mkaulig does this mean you're successfully hitting your graphcool endpoint and decoding the responses successfully using `graphqelm`? If so, neat! I think between that and the Github API, there's not much else you could throw at the code generator.

**Comment by mkaulig** [comment]
Yes, right now I converted just one of the queries of my app, but it's working great so far and nothing is missing!

**Comment by dillonkearns** [comment]
That's outstanding, so glad to hear it!
