### ISSUE TITLE
Feedback wanted on `Interface` and `Union` code generation

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/graphqelm#14]
Here's [an example](https://github.com/dillonkearns/graphqelm/blob/5ef578d114d5c97592b857671387e97e2a013d86/examples/src/Starwars.elm#L40-L48) of code of consuming an interface, and this is the result. Note that `selection` takes a list of `SelectionSet`s in addition to a selection of common fields from the Character interface, while `baseSelection` only takes the selection of common fields.

<img width="187" alt="__src_starwars_elm" src="https://user-images.githubusercontent.com/1384166/34502053-a1596938-efc6-11e7-8a84-7c9ed057f71d.png">

**Comment by dillonkearns** [comment]
I'm considering using a different namespace to make it more clear that it is an Interface.

So
```elm
hero : SelectionSet Character Swapi.Object.Character
```
would become

```elm
hero : SelectionSet Character Swapi.Interface.Character
```
And similarly Unions would be annotated with `Swapi.Union.SomeUnionType`. The drawback is that there is more for the user to import, which could cause confusion. On the other hand, you would get the benefit of things being grouped nicely into folders based on their type.

**Comment by martimatix** [comment]
I'm in favour for making the change. More imports but I like the distinction between interface and unions.

**Comment by dillonkearns** [comment]
👍 Cool, I think that's the right call, too.

Any thoughts on the naming here? Is it confusing that `selection` on Objects and `baseSelection` on Interfaces are the same function, and `selection` on Interfaces takes an extra argument (list of `FragmentSelectionSet`s)? I feel pretty good about it, but I wonder if there's something a little more intuitive that captures that clearly, while honoring the GraphQL domain language.

I'm also considering whether it would be useful to generate a function for Interfaces that's the inverse of `baseSelection`... that only selects the distinct fields, no common ones. But that seems like it might be cluttering it up too much and I'm not sure if there's a strong case for it. Maybe wait and see if there's interest when people start using it in wild before adding something like this?

**Comment by martimatix** [comment]
The names make sense to me and I can't think of anything better. It's not confusing if one understands the relationship between interfaces and objects in graphql.

As for the inverse of `baseSelection` - I don't know at this point if there's a need for it. If it were me, I'd probably hold off on that feature until someone encounters a use case.

**Comment by dillonkearns** [comment]
Great, thanks for letting me bounce those ideas off of you Mario! I think this will be ready to publicize more this week. It'll be good to collect more use cases and see what new users find confusing.

**Comment by dillonkearns** [comment]
FYI @martimatix I changed the name from `baseSelection` to `commonSelection` to be more in line with the language used in the GraphQL spec, as in [the section on interfaces](http://facebook.github.io/graphql/October2016/#sec-Interface), for example.
