### ISSUE TITLE
Encode.float is missing

### ISSUE THREAD

**Issue by Augustin82** [dillonkearns/graphqelm#18]
There is Encode.int/string/etc. but not float =)

It's a simple matter of adding:
```
{-| Encode an float
-}
float : Float -> Value
float value =
    Json.Encode.float value
        |> Json
```

to `Graphqelm/Encode.elm`.

**Comment by dillonkearns** [comment]
Nice catch, thank you for reporting the issue @Augustin82! This fix will go out today.

I think I'll also move the module to `Graphqelm.Internal.Encode` to make it more clear in the documentation that only the generated code consumes this.

**Comment by dillonkearns** [comment]
This is fixed in the latest release: http://package.elm-lang.org/packages/dillonkearns/graphqelm/5.0.0/Graphqelm-Internal-Encode#float

I also went ahead and renamed the module to `Graphqelm.Internal.Encode`. Thanks again @Augustin82!
