### ISSUE TITLE
Duplicate generated function names

### ISSUE THREAD

**Issue by sporto** [dillonkearns/graphqelm#19]
We have this in our ruby definition:

```
field :year_budget, types.Int, deprecation_reason: "Use yearBudget"
field :yearBudget, types.Int, property: :year_budget
```

Which generates:
``` 
{
  "name": "yearBudget",
  ...
 },
 {
    "name": "year_budget",
      ...
}
```
graphqelm generates:

```
yearBudget : FieldDecoder (Maybe Int) Api.Object.Client
yearBudget =
    Object.fieldDecoder "yearBudget" [] (Decode.int |> Decode.maybe)

yearBudget : FieldDecoder (Maybe Int) Api.Object.Client
yearBudget =
    Object.fieldDecoder "year_budget" [] (Decode.int |> Decode.maybe)
```

So two functions with the same name. I think that graphqelm needs to make a distinction between camelCase and snake_case somehow. Thanks.

**Comment by dillonkearns** [comment]
This should be resolved now, see https://github.com/dillonkearns/graphqelm/issues/21#issuecomment-357474582. Let me know how the upgrade goes!

**Comment by sporto** [comment]
This is fixed now, thanks. Closing.
