### ISSUE TITLE
Expose Error

### ISSUE THREAD

**Issue by sporto** [dillonkearns/graphqelm#20]
If I get an Error (Graphqelm.Http.Error) I cannot do anything with it. I need to pattern match on the constructors in order to log the error. e.g.

```
logGraphQLError : Graphqelm.Http.Error -> Cmd msg
logGraphQLError error =
    case error of
        Graphqelm.Http.HttpError e ->
            logHttpError e

        Graphqelm.Http.GraphqlError errors ->
            ...
```

But the constructors are not exposed. Please expose the constructors i.e. `exposing Error(..)`

**Comment by dillonkearns** [comment]
@sporto thank you so much for reporting this issue! This is resolved with elm package version 6.0.0 (at this rate we'll be at version 1000 pretty soon!).
