### ISSUE TITLE
How to provide an attribute as constant

### ISSUE THREAD

**Issue by sporto** [dillonkearns/graphqelm#22]
I have a record like:

```
type alias Thing =
   { id: String
    , name: String
    , isBusy: Bool
   }
```

`id` and `name` come from the Graphql api. But `isBusy` is made up in the FE so we can provide feedback to the user.

I don't think there is a way to add this constant atm, is there? e.g.

```
|> with (Thing.id)
|> with (Thing.name)
|> with (????)
```

Maybe `Graphqelm.SelectionSet` is missing a `constant` function?

```
|> with (Thing.id)
|> with (Thing.name)
|> constant False
```

**Comment by dillonkearns** [comment]
Great suggestion, this definitely belongs in there. Added! Thanks!

http://package.elm-lang.org/packages/dillonkearns/graphqelm/6.1.0/Graphqelm-SelectionSet#hardcoded
