### ISSUE TITLE
Feedback while generating files

### ISSUE THREAD

**Issue by martimatix** [dillonkearns/graphqelm#28]
I just ran graphqelm on the GitHub and it took about a minute to generate the files. For a one minute wait, some users might be think: "Is this thing working?"

Therefore, it would be nice to give some sort of feedback while files are being generated.

**Comment by dillonkearns** [comment]
Hey Mario, thanks for filing the issue! That's really interesting that it takes that long for you, it consistently takes 15 seconds or so for me:

```shell
$ time ./bin/graphqelm https://api.github.com/graphql --header 'authorization: Bearer <token>' --base Github --includeDeprecated --output examples/src
./bin/graphqelm https://api.github.com/graphql --header  --base Github
43.87s user 15.89s system 497% cpu 12.000 total
```

Not that that changes anything about your suggestion, just kind of interesting. Adding in a little message to let people know that it's working sounds like a great idea! I'll add that in as part of the next release. Thanks for the suggestion!

**Comment by martimatix** [comment]
That's interesting. Here are my stats:

```
$ time graphqelm https://api.github.com/graphql --header 'Authorization: Bearer <token>' --base Github
       67.03 real       171.58 user        11.57 sys
```
Running this on a 2017 Macbook Pro with an i5 processor.

**Comment by martimatix** [comment]
OK, this is really weird. My 2014 Macbook Pro, it's much shorter and the machine doesn't lock up.

```
graphqelm https://api.github.com/graphql --header  --base Github  35.42s user 10.77s system 228% cpu 20.218 total
```

Probably something weird going on with my installation on my newer machine.

**Comment by dillonkearns** [comment]
That is interesting, I wonder why that could be. Let me know if you have any ideas, I definitely want to keep the code generation really snappy.

I added some log statements, in npm version `2.1.3` the output now looks like this:
```
Fetching GraphQL schema...
Generating files...
Success!
```

I'll close this for now, but let me know if you have any suggestions on how to change the output. Thanks again for the suggestion!
