### ISSUE TITLE
Type aliases for optional and required arguments

### ISSUE THREAD

**Issue by sporto** [dillonkearns/graphqelm#31]
In queries the generator adds signatures for optional arguments like:

```
viewer : ({ adjustments : OptionalArgument (List Api.Enum.Foo), ...) } -> { adjustments : OptionalArgument (List Api.Enum.Foo), ...) -> ... Field decodesTo Api.Object.Root
```

We have a function that use in many places that will take a record we have and populate the correct optional arguments:

```
optionalArgumentsForFilter  filter optionalArgs =
     {  optionalArgs | adjustments = .... }
```

So we can use this like:

```
|> with (Api.Object.Root.viewer  (optionalArgumentsForFilter filter) requiredArgs viewer
```

To have a nice type signature in `optionalArgumentsForFilter` we need to duplicate code from the generated code:

```
type alias OptionalArgs = 
   { adjustments : OptionalArgument (List Api.Enum.Foo), ...) }

optionalArgumentsForFilter  : Filter -> OptionalArgs -> OptionalArgs
```

This creates repetition and breaks when the generated code changes.
It would be nicer if the generator created type aliases so they can be imported.

```
import Api.Object.Root exposing (ViewerOptionalArgs)

optionalArgumentsForFilter  : Filter -> ViewerOptionalArgs -> ViewerOptionalArgs
```

**Comment by dillonkearns** [comment]
Hey Sebastian, thanks for filing this issue that's an excellent suggestion.

To use [the StarWars code](https://github.com/dillonkearns/graphqelm/blob/master/examples/src/Starwars.elm) as an example, I would imagine something like this:

```haskell
type alias DroidArgsRequired =
    { id : Swapi.Scalar.Id }

droid : DroidArgsRequired -> SelectionSet decodesTo Swapi.Object.Droid -> Field (Maybe decodesTo) RootQuery
-- ...

type alias HeroArgsOptional =
    { episode : OptionalArgument Swapi.Enum.Episode.Episode }

hero : (HeroArgsOptional -> HeroArgsOptional) -> SelectionSet decodesTo Swapi.Interface.Character -> Field decodesTo RootQuery
-- ...
```

What do you think of that naming convention?

**Comment by sporto** [comment]
I think is fine. 

However as you already named optional arguments `OptionalArgument`, maybe it makes sense something like `HeroOptionalArguments` so it feels more consistent?

Either way is fine.

**Comment by dillonkearns** [comment]
Great point, 👍 for consistency.

**Comment by dillonkearns** [comment]
@sporto The latest npm package is now generating type aliases for optional arguments. I will try to add the code generation for required argument type aliases before my trip tomorrow!

Let me know if there's anything you think could be improved with it. Thanks!

**Comment by dillonkearns** [comment]
@sporto it is now generating type aliases for required args as well, I think it's all set now! Feel free to reply if you see issues or have suggestions though.
