### ISSUE TITLE
`name` and `Name` fields generate ambiguous function names

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/graphqelm#34]
@nicolasartman reported this compilation error. The cause appears to be that there is a field in the query named `user` and a field named `User`. These field names both normalize to `user` for their function names in the `Query` module.

> For the User object (and only that one it seems), it generates two functions with the same name:

```haskell
{-|

  - auth0UserId -
  - id -
-}
user : ({ auth0UserId : OptionalArgument String, id : OptionalArgument API.Scalar.Id } -> { auth0UserId : OptionalArgument String, id : OptionalArgument API.Scalar.Id }) -> SelectionSet decodesTo API.Object.User -> Field (Maybe decodesTo) RootQuery
user fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { auth0UserId = Absent, id = Absent }

        optionalArgs =
            [ Argument.optional "auth0UserId" filledInOptionals.auth0UserId Encode.string, Argument.optional "id" filledInOptionals.id (\(API.Scalar.Id raw) -> Encode.string raw) ]
                |> List.filterMap identity
    in
        Object.selectionField "User" optionalArgs object (identity >> Decode.maybe)
user : SelectionSet decodesTo API.Object.User -> Field (Maybe decodesTo) RootQuery
user object =
    Object.selectionField "user" [] object (identity >> Decode.maybe)
```

> This, as expected, fails compilation due to top-level identifier ambiguity.

@nicolasartman, did I diagnose the issue correctly here? Is it true that your API has both `user` and `User` fields under query?

This package has to make certain choices about how to normalize names so that they are valid in Elm. Like in this case, function names must start with a lowercase letter, so to normalize them we just change the first letter to be lowercase if it isn't.

Can you explain to me the purpose of your schema using both of these names? Is this a Graph.cool convention, or something that you or your team put in there? It's important for me to get a good sense of the use case to figure out what to do here. Thank you!

**Comment by nicolasartman** [comment]
Yep, you nailed it!

I'm looking into it and it appears that my project contains both a User type and a user type, and I'm honestly not sure why. I've reached out to graphcool to better understand why this is, because I can't find the lowercase variant anywhere in their system except the query interface. I'll update here once I figure out exactly what's going on.

My intention is just to have a User type, so I don't actually have a use-case for having both at this time.

**Comment by dillonkearns** [comment]
Great, thanks for the quick response! It would be nice to be able to assume that this case will not occur because otherwise it would create some messy normalization that would not be ideal.

Let me know what you find out about why this is happening, hopefully there's a bug somewhere and it goes away when it's fixed. Thanks!

**Comment by Frozen666** [comment]
I am guessing this is an artifact generated by graphcool. There is only one User type, but two queries are generated:
Query.User(
id: ID
): User
and
Query.user: User

where the latter does not seem to do anything useful.

**Comment by dillonkearns** [comment]
@Frozen666 do you get why it generates both of those? I'm having trouble imaging why that would be and what the reasoning behind the naming convention is.

**Comment by Frozen666** [comment]
The "user" query was changed to "me" in their other service called Prisma. They are currently working mainly on Prisma and plan to synchronize Graphcool later... so I guess they will change the name later as well. For now I can just remove the generated "user" function in the Query.elm until this happens.

**Comment by dillonkearns** [comment]
Ah, okay, thanks for clarifying, that's really good to know. So it sounds like this is deprecated essentially by Graph.cool and will by changing in the future. And working around is not too painful (by just deleting or renaming manually after generating code).

Is it reasonable to close this issue for now unless I hear that this is causing more pain or that there are other use cases? The alternative would be to come up with some sort of normalization strategy. But I want to keep the normalization context free as it is now (i.e. you can normalize a name without knowing the names of any other things). So we'd have to introduce some strange rule like turn `Name` => `n_ame` or `nAme` or `capitalName` or something hacky or verbose like that to indicate that it's different from `name`. And this could be suboptimal for codebases where they don't have any names that are exactly the same besides casing, but perhaps they use some capital names.

It's a lot to think about, but essentially are you two okay with assuming for now that there will be no case-insensitive duplicates, or if there are that they will use the workaround?

**Comment by nicolasartman** [comment]
Absolutely. Thank you for looking into it and getting their response
@frozen666! And thanks for thinking through this and facilitating such
excellent discussion of these issues @dillonkearns.

I think the assumption that other APIs won’t do this seems completely
reasonable. I’m going to delete the extra function manually when I generate
the files until graphcool updates.

**Comment by dillonkearns** [comment]
Great, thank you both for the insights here! I'll close this for now, but don't hesitate to restart the discussion of you have anything else to add.
