### ISSUE TITLE
`Api.Object` does not expose `Query`

### ISSUE THREAD

**Issue by martimatix** [dillonkearns/graphqelm#4]
In the Github API, under Query, there is a field called `Relay` that gives back a type of `Query`.

In the generated Elm code, this is defined as:

```elm
relay : SelectionSet relay Api.Object.Query -> FieldDecoder relay RootQuery
relay object =
    Object.single "relay" [] (object)
```

However, `Api.Object.Query` is not defined and therefore, the Elm code cannot be compiled.

**Comment by dillonkearns** [comment]
Thanks for the report! I'm working on a fix for this. Using `RootQuery` instead of `Api.Object.Query` there does the trick. I think I'll have a fix in tomorrow.

**Comment by dillonkearns** [comment]
I pushed a fix! It doesn't handle all cases yet, but it handles the Github Api relay reference.

**Comment by dillonkearns** [comment]
Alright, it now handles self-referring RootQuery objects and RootMutation objects. Should be good to go.

**Comment by martimatix** [comment]
Haven't had a chance to test this but it's great that these fixes are going in so quickly. :+1:

**Comment by dillonkearns** [comment]
My pleasure, thanks for the help getting things polished! I've got 7 more items on the Trello board that I consider to be the core (to varying degrees, mostly the core items are done and stable really). It'll be nice to knock the last few off of there!
