### ISSUE TITLE
Field name clash with Elm reserved words

### ISSUE THREAD

**Issue by madsflensted** [dillonkearns/graphqelm#40]
I have a simple schema with this object definition

```graphql
type Service {
  name : String
  port :  Int
}
```
This causes graphqelm to throw an error, which actually seems to come from elm-format. The error message is formated weird so I won't paste it here.

Looking at the generated code (and the elm-format error) it was clear that `port` can not be used as a field name. I expect the same will be true for other words like `module` and `import`.

This is not a big problem, so this issue is more to see if it was possible to catch this naming clash with relevant reserved words in Elm and display a better error message.

**Comment by dillonkearns** [comment]
Hello @madsflensted, thank you for reporting the issue! Yes, I’m handling the reserved word `type` right now but for some reason I forgot to add others! The normalization code should be handling this. The strategy I’m using is to just add a trailing `_`, so in this case the field would be called `port_`. I won’t be at a computer for a couple of weeks, but I’ll make this change as soon as I’m back home! Here’s the relevant file: https://github.com/dillonkearns/graphqelm/blob/a9bbff3d18968684d9a968f32983ce837ec8c449/src/Graphqelm/Generator/Normalize.elm#L9.

**Comment by dillonkearns** [comment]
Resolved by #41, now fixed in npm version 3.1.8!
