### ISSUE TITLE
Support multipart/form-data for file uploads

### ISSUE THREAD

**Issue by itsgreggreg** [dillonkearns/graphqelm#50]
https://hexdocs.pm/absinthe/file-uploads.html

there's currently no way to upload a file without encoding it as a string.

**Comment by itsgreggreg** [comment]
I just realized that being able to even do this relies on a native extension I've been using for handling file blobs.

In any case if 0.19.0 🙏 supports file refs / blobs we'll need multipart post bodies to support file uploads.

**Comment by dillonkearns** [comment]
Hey @itsgreggreg, interesting I didn't know that GraphQL supported that. Can we close this for now and revisit it once Elm has support for it? Also, once we revisit it it would be helpful to see some Elm code to demonstrate how you're doing that so I can wrap my head around it a little better. Thanks!

**Comment by itsgreggreg** [comment]
sounds good to me!

**Comment by xtian** [comment]
> Hey @itsgreggreg, interesting I didn't know that GraphQL supported that. 

Just FYI: I believe this functionality is an unofficial extension to GraphQL provided by Absinthe.
