### ISSUE TITLE
Access to schemas protected by token auth

### ISSUE THREAD

**Issue by tmattio** [dillonkearns/graphqelm#51]
I am trying to generate the Github GraphQL API like in the examples. As I enabled two-factor authentication for my account, I need to provide a token to access the API: https://developer.github.com/v4/guides/forming-calls/#communicating-with-graphql

Is there any way to do this with the current command line interface?

PS: I just found this package, this is great work, thank you so much for the work you put into it!

**Comment by dillonkearns** [comment]
Hey @tmattio, I’m glad to hear that you’re happy with the library!

I think this `--header` CLI flag is what you’re looking for: https://github.com/dillonkearns/graphqelm/blob/master/package.json#L11.

**Comment by tmattio** [comment]
@dillonkearns Exactly what I was looking for, thank you!

**Comment by chevinbrown** [comment]
@dillonkearns can we get this added to the Readme? It should be intuitive, but I found myself here. 😄 
I'll be happy to provide that PR.

❤️

**Comment by dillonkearns** [comment]
@chevinbrown yes, absolutely, great idea! I would welcome a PR to add that to the README 👍

**Comment by chevinbrown** [comment]
#81
