### ISSUE TITLE
Send Example Not Working

### ISSUE THREAD

**Issue by ghivert** [dillonkearns/graphqelm#53]
Hi!

I wanted to upgrade my version of GraphQelm, and got stuck with your example.

```elm
import Graphqelm.Http
import Graphqelm.OptionalArgument exposing (OptionalArgument(Null, Present))
import RemoteData exposing (RemoteData)

type Msg
    = GotResponse RemoteData Graphqelm.Http.Error Response

makeRequest : Cmd Msg
makeRequest =
    query
        |> Graphqelm.Http.queryRequest "https://graphqelm.herokuapp.com/"
        |> Graphqelm.Http.withHeader "authorization" "Bearer abcdefgh12345678"
        -- If you're not using remote data, it's just
        -- |> Graphqelm.Http.send GotResponse
        -- With remote data, it's as below
        |> Graphqelm.Http.send (RemoteData.fromResult >> GotResponse)
```

I don't even see how it could work. Actually, `RemoteData.fromResult` will have a signature of `Result (Graphelm.Http.Error decodesTo) decodesTo -> RemoteData (Graphqelm.Http.Error decodesTo) decodesTo`. 

In our application, we were doing a transformation like `Result Graphqelm.Http.Error Response -> RemoteData Graphqelm.Http.Error Layout` and sending directly the RemoteData in the message. Now, we need to have messages able to deal with `RemoteData (Graphqelm.Http.Error decodesTo) Layout`.

Is this the desired behavior? Because it looks like creating noise in the messages, like having to deal with `Graphqelm.Http.Error thing` rather than just `Graphqelm.Http.Error`.

I maybe missed something so if you can enlighten me! 😄

**Comment by dillonkearns** [comment]
@ghivert I believe it's safe to close this issue now, but please feel free to reply if that's not the case. Thanks!
