### ISSUE TITLE
Code generation for Enums

### ISSUE THREAD

**Issue by BinaryHexer** [dillonkearns/graphqelm#59]
I would like to know if we can change the way code is generated for Enums, so it is more helpful and inclusive without changing the functionality of the said code.

Current:
```
module Request.Graphql.Enum.JobStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Submitted -
  - Started -
  - Finished -
  - Pausing -
  - Paused -
  - Cancelled -
  - Failed -
-}
type JobStatus
    = Submitted
    | Started
    | Finished
    | Pausing
    | Paused
    | Cancelled
    | Failed


decoder : Decoder JobStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "SUBMITTED" ->
                        Decode.succeed Submitted

                    "STARTED" ->
                        Decode.succeed Started

                    "FINISHED" ->
                        Decode.succeed Finished

                    "PAUSING" ->
                        Decode.succeed Pausing

                    "PAUSED" ->
                        Decode.succeed Paused

                    "CANCELLED" ->
                        Decode.succeed Cancelled

                    "FAILED" ->
                        Decode.succeed Failed

                    _ ->
                        Decode.fail ("Invalid JobStatus type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : JobStatus -> String
toString enum =
    case enum of
        Submitted ->
            "SUBMITTED"

        Started ->
            "STARTED"

        Finished ->
            "FINISHED"

        Pausing ->
            "PAUSING"

        Paused ->
            "PAUSED"

        Cancelled ->
            "CANCELLED"

        Failed ->
            "FAILED"
```

Proposed:
```
type JobStatus
    = Submitted
    | Started
    | Finished
    | Pausing
    | Paused
    | Cancelled
    | Failed


typeMap : List ( String, JobStatus )
typeMap =
    [ ( "SUBMITTED", Submitted )
    , ( "STARTED", Started )
    , ( "FINISHED", Finished )
    , ( "PAUSING", Pausing )
    , ( "PAUSED", Paused )
    , ( "CANCELLED", Cancelled )
    , ( "FAILED", Failed )
    ]


allStatus : List JobStatus
allStatus =
    List.map Tuple.second typeMap


decoder : Decoder JobStatus
decoder =
    mapDecoder typeMap


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : JobStatus -> String
toString =
    typeMapToString typeMap



-- Generic Helpers, usually in their own module


mapDecoder : List ( String, a ) -> Decoder a
mapDecoder allPairs =
    let
        findIn pairs str =
            case pairs of
                ( k, v ) :: rest ->
                    if k == str then
                        Decode.succeed v
                    else
                        findIn rest str

                [] ->
                    Decode.fail (str ++ " is an invalid key")
    in
    Decode.string |> Decode.andThen (findIn allPairs)


typeMapToString : List ( String, a ) -> a -> String
typeMapToString allPairs key =
    List.filterMap
        (\( k, v ) ->
            if v == key then
                Just k
            else
                Nothing
        )
        allPairs
        |> List.head
        |> Maybe.withDefault "Serialization Failed"
```

This was inspired by this [post](https://www.reddit.com/r/elm/comments/8i3b0t/better_handling_enums/) on reddit.

**Comment by dillonkearns** [comment]
Hey @BinaryHexer, thanks for the discussion. I like to drive all features based on a concrete need, could you describe how you would use the added code here for your specific use case? It seems to me that this module is attempting to abstract away the low-level details of how to serialize/de-serialize Enums between Elm-GraphQL. So I think it might actually be undesireable to open up low-level details of serialization since the goal is to abstract his away. I’m open to ideas if I’m missing a specific use case where this would be helpful, though! Thanks!

**Comment by BinaryHexer** [comment]
So I completely understand your hesitation to rush in and add more _features_ and bloat this library unnecessarily, but humor me.  

For example what I have here is an enum that is used both as part of the (graphQL) Input and also as part of the returned record.  

In the absence of the proposed extra functions, the only option is to implement themselves by hand, which means you have to start caring about keeping them in Sync, etc and I think the objective of this library is to abstract away all the concerns related to writing type safe and correct GraphQL code by just pointing at the correct graphQL endpoint or schema.

If you feel that such defaults are _too much_, can I propose some sort of flag like `-generate-extra-helpers` for the graphqelm tool, so that those who want it can have it and at the same time it does not generate too much extra code for those who do not want it.

I think most users of your library would appreciate that there is an option to get such extra helper functions for _free_ if they want it.

**Comment by dillonkearns** [comment]
Hey @BinaryHexer If I’m understanding you correctly, the functionality you’re describing is already abstracted away by Graphqelm so there is no need to do the low-level work of serializes/deserializing Enums at any point. In fact, the way Graphqelm is structured it would be impossible to do that, Graphqelm completely handles serializing/deserializing Enums before you send a request/as soon as you receive data.

I’m not at a computer right now so I can’t give you an Ellie example, but try building the following request using either the Ellie example in the README or the `StarWars.elm` file in the examples folder as a starting point and I think you’ll see what I mean:

```
{
  hero(episode: JEDI) { name }
}
```

You’ll notice that when you build this using Graphqelm, you’re not sending a String, but instead you pass the argument as an `Episode` union value. So there’s no serialization needed. So there’s no place that you’ll need the low-level serialization/de-serialization logic.

Try that exercise and see if that makes sense! Cheers!

**Comment by dillonkearns** [comment]
Hi @BinaryHexer, is my message making sense? Let me know if you need clarification. I'm going to close this issue for now, but if it turns out that I missed something, feel free to re-open this. I'm happy to discuss this more if you have other thoughts. Thanks!
