### ISSUE TITLE
Getting `Ok` even though POST response includes errors

### ISSUE THREAD

**Issue by ahstro** [dillonkearns/graphqelm#61]
I'm doing a request to our GraphQL-server that results in a response similar to this:
```json
{
  "data": {
    "someData": {},
    "otherData": null
    }
  },
  "errors": {
    "message": "Couldn't get otherData"
  }
}
```
I expected graphqelm to return an `Err (Graphqelm.Http.Error MyData)`, but instead I got an `Ok MyData`, which means there's no way of knowing if an error occurred with the request. This has happened with all requests that have produced errors.

**Comment by xtian** [comment]
@ahstro: `errors` should be a list, not an object. See http://graphql.org/learn/serving-over-http/#response

**Comment by ahstro** [comment]
@xtian I'll go shake my fist at our backenders and see if that fixes it. Thanks :)

**Comment by ahstro** [comment]
Yup, that was it. Thank you! :smile:

**Comment by dillonkearns** [comment]
💯@xtian thank you so much for helping out here!
